const Types = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    START_LOADING: "START_LOADING",
    STOP_LOADING: "STOP_LOADING",
    SET_RESPONSE: "SET_RESPONSE",
    REMOVE_RESPONSE: "REMOVE_RESPONSE",
    RELOAD: "RELOAD",
    // crud types
    ADD_DATA: "ADD_DATA",
    UPDATE_DATA: "UPDATE_DATA",
    GET_ALL_DATA: "GET_ALL_DATA",
    //season
    ADD_SEASON: "ADD_SEASON",
    CLEAR_SEASON: "CLEAR_SEASON",
    SWITCH_SEASON: "SWITCH_SEASON",
}
export default Types;