const Define = {
    USERINFO_LOCAL: "USERINFO_LOCAL",
    SEASONINFO_LOCAL: "SEASONINFO_LOCAL",
    DATE_FORMAT: "YYYY-MMMM-DD",
    DATE_FORMAT_SIMPLE: "YYYY-MM-DD",
    NO_TYPE: "NO_TYPE",
    MIL_TYPE: "MIL_TYPE",
    KACHA_TYPE: "KACHA_TYPE",
    PAKA_TYPE: "PAKA_TYPE",
    JAB_TYPE: "JAB_TYPE",
}
export default Define;